export type QuickFood = {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export const quickFoodCategories: Record<string, QuickFood[]> = {
  "🥣 Kahvaltı": [
    { name: "Yumurta (haşlanmış, 1 adet)", calories: 78, protein: 6, carbs: 1, fat: 5 },
    { name: "Yumurta (sahanda, 1 adet)", calories: 90, protein: 6, carbs: 1, fat: 7 },
    { name: "Menemen (1 porsiyon)", calories: 200, protein: 10, carbs: 8, fat: 14 },
    { name: "Ekmek (tam buğday, 1 dilim)", calories: 80, protein: 4, carbs: 15, fat: 1 },
    { name: "Ekmek (beyaz, 1 dilim)", calories: 70, protein: 2, carbs: 13, fat: 1 },
    { name: "Simit (1 adet)", calories: 230, protein: 7, carbs: 46, fat: 2 },
    { name: "Poğaça (1 adet)", calories: 250, protein: 6, carbs: 30, fat: 12 },
    { name: "Peynir (beyaz, 30g)", calories: 75, protein: 5, carbs: 1, fat: 6 },
    { name: "Peynir (kaşar, 30g)", calories: 110, protein: 7, carbs: 0, fat: 9 },
    { name: "Peynir (lor, 50g)", calories: 60, protein: 7, carbs: 2, fat: 3 },
    { name: "Zeytin (10 adet)", calories: 60, protein: 0, carbs: 1, fat: 6 },
    { name: "Domates (1 orta boy)", calories: 25, protein: 1, carbs: 5, fat: 0 },
    { name: "Salatalık (1 adet)", calories: 15, protein: 1, carbs: 3, fat: 0 },
    { name: "Bal (1 yemek kaşığı)", calories: 64, protein: 0, carbs: 17, fat: 0 },
    { name: "Tereyağı (1 tatlı kaşığı)", calories: 72, protein: 0, carbs: 0, fat: 8 },
    { name: "Reçel (1 yemek kaşığı)", calories: 56, protein: 0, carbs: 14, fat: 0 },
    { name: "Tahin (1 yemek kaşığı)", calories: 89, protein: 3, carbs: 4, fat: 8 },
    { name: "Sucuk (2 dilim)", calories: 160, protein: 7, carbs: 1, fat: 14 },
  ],
  "🍗 Et & Protein": [
    { name: "Tavuk göğsü (100g)", calories: 165, protein: 31, carbs: 0, fat: 4 },
    { name: "Tavuk but (100g, deri yok)", calories: 175, protein: 28, carbs: 0, fat: 7 },
    { name: "Tavuk çorba (1 kase)", calories: 120, protein: 12, carbs: 10, fat: 4 },
    { name: "Izgara tavuk (1 porsiyon)", calories: 200, protein: 38, carbs: 0, fat: 5 },
    { name: "Kırmızı et (100g, yağsız)", calories: 190, protein: 26, carbs: 0, fat: 10 },
    { name: "Köfte (3 adet)", calories: 180, protein: 18, carbs: 5, fat: 10 },
    { name: "Izgara köfte (1 porsiyon)", calories: 220, protein: 24, carbs: 5, fat: 12 },
    { name: "Balık (levrek, 100g ızgara)", calories: 97, protein: 19, carbs: 0, fat: 2 },
    { name: "Balık (somon, 100g)", calories: 208, protein: 20, carbs: 0, fat: 13 },
    { name: "Balık (hamsi, 100g)", calories: 130, protein: 20, carbs: 0, fat: 5 },
    { name: "Ton balığı (1 kutu, su ile)", calories: 120, protein: 28, carbs: 0, fat: 1 },
    { name: "Karides (100g)", calories: 85, protein: 18, carbs: 1, fat: 1 },
    { name: "Hindi (100g)", calories: 135, protein: 30, carbs: 0, fat: 1 },
    { name: "Sosis (1 adet)", calories: 100, protein: 5, carbs: 2, fat: 9 },
    { name: "Yumurta (haşlanmış, 2 adet)", calories: 156, protein: 12, carbs: 2, fat: 10 },
  ],
  "🥗 Sebze & Salata": [
    { name: "Yeşil salata (1 porsiyon)", calories: 30, protein: 2, carbs: 5, fat: 0 },
    { name: "Çoban salatası (1 porsiyon)", calories: 65, protein: 2, carbs: 10, fat: 2 },
    { name: "Sezar salata (1 porsiyon)", calories: 180, protein: 7, carbs: 10, fat: 14 },
    { name: "Mercimek çorbası (1 kase)", calories: 150, protein: 8, carbs: 25, fat: 3 },
    { name: "Domates çorbası (1 kase)", calories: 100, protein: 3, carbs: 15, fat: 4 },
    { name: "Sebze çorbası (1 kase)", calories: 80, protein: 3, carbs: 12, fat: 2 },
    { name: "Brokoli (100g, buharda)", calories: 34, protein: 3, carbs: 7, fat: 0 },
    { name: "Havuç (1 orta boy)", calories: 30, protein: 1, carbs: 7, fat: 0 },
    { name: "Ispanak (100g, pişmiş)", calories: 41, protein: 5, carbs: 4, fat: 0 },
    { name: "Patates (1 orta boy, haşlanmış)", calories: 130, protein: 3, carbs: 30, fat: 0 },
    { name: "Tatlı patates (100g)", calories: 90, protein: 2, carbs: 21, fat: 0 },
    { name: "Biber dolması (2 adet)", calories: 180, protein: 8, carbs: 22, fat: 7 },
    { name: "Zeytinyağlı fasulye (1 porsiyon)", calories: 160, protein: 5, carbs: 20, fat: 7 },
    { name: "Karnıyarık (1 porsiyon)", calories: 250, protein: 12, carbs: 18, fat: 15 },
    { name: "İmam bayıldı (1 porsiyon)", calories: 180, protein: 3, carbs: 15, fat: 12 },
    { name: "Türlü (1 porsiyon)", calories: 120, protein: 4, carbs: 18, fat: 5 },
    { name: "Bezelye (100g)", calories: 80, protein: 5, carbs: 15, fat: 0 },
    { name: "Mısır (1 koçan)", calories: 130, protein: 5, carbs: 27, fat: 2 },
  ],
  "🍚 Karbonhidrat": [
    { name: "Pilav (1 porsiyon, 200g)", calories: 200, protein: 4, carbs: 45, fat: 1 },
    { name: "Bulgur pilavı (1 porsiyon)", calories: 180, protein: 5, carbs: 38, fat: 2 },
    { name: "Makarna (1 porsiyon, 200g)", calories: 220, protein: 8, carbs: 44, fat: 2 },
    { name: "Makarna (tam buğday, 200g)", calories: 200, protein: 8, carbs: 40, fat: 2 },
    { name: "Lazanya (1 porsiyon)", calories: 350, protein: 15, carbs: 40, fat: 15 },
    { name: "Börek (ıspanaklı, 1 dilim)", calories: 280, protein: 8, carbs: 25, fat: 17 },
    { name: "Börek (peynirli, 1 dilim)", calories: 300, protein: 10, carbs: 25, fat: 18 },
    { name: "Su böreği (1 dilim)", calories: 260, protein: 10, carbs: 28, fat: 13 },
    { name: "Gözleme (peynirli, 1 adet)", calories: 320, protein: 12, carbs: 35, fat: 16 },
    { name: "Gözleme (ıspanaklı, 1 adet)", calories: 280, protein: 10, carbs: 33, fat: 13 },
    { name: "Pide (1 dilim)", calories: 250, protein: 8, carbs: 40, fat: 8 },
    { name: "Lahmacun (1 adet)", calories: 200, protein: 10, carbs: 30, fat: 6 },
    { name: "Döner (et, 1 porsiyon)", calories: 400, protein: 30, carbs: 10, fat: 26 },
    { name: "Sandviç (tam buğday)", calories: 280, protein: 15, carbs: 35, fat: 8 },
    { name: "Ekmek (2 dilim)", calories: 160, protein: 6, carbs: 30, fat: 2 },
    { name: "Baklava (2 dilim)", calories: 450, protein: 5, carbs: 55, fat: 25 },
  ],
  "🥛 Süt & Yoğurt": [
    { name: "Yoğurt (sade, 150g)", calories: 90, protein: 8, carbs: 10, fat: 2 },
    { name: "Yoğurt (tam yağlı, 150g)", calories: 130, protein: 7, carbs: 9, fat: 7 },
    { name: "Yoğurt (meyveli, 125g)", calories: 120, protein: 5, carbs: 20, fat: 2 },
    { name: "Süzme yoğurt (100g)", calories: 100, protein: 10, carbs: 5, fat: 4 },
    { name: "Ayran (1 bardak, 250ml)", calories: 60, protein: 4, carbs: 5, fat: 2 },
    { name: "Süt (yarım yağlı, 1 bardak)", calories: 100, protein: 8, carbs: 12, fat: 3 },
    { name: "Süt (tam yağlı, 1 bardak)", calories: 150, protein: 8, carbs: 11, fat: 8 },
    { name: "Kefir (1 bardak)", calories: 100, protein: 8, carbs: 10, fat: 3 },
    { name: "Sütlaç (1 porsiyon)", calories: 200, protein: 6, carbs: 38, fat: 4 },
    { name: "Muhallebi (1 porsiyon)", calories: 190, protein: 5, carbs: 35, fat: 4 },
    { name: "Kazandibi (1 porsiyon)", calories: 220, protein: 6, carbs: 40, fat: 5 },
  ],
  "🍎 Meyve": [
    { name: "Elma (1 orta boy)", calories: 95, protein: 0, carbs: 25, fat: 0 },
    { name: "Muz (1 adet)", calories: 105, protein: 1, carbs: 27, fat: 0 },
    { name: "Portakal (1 adet)", calories: 65, protein: 1, carbs: 16, fat: 0 },
    { name: "Mandalina (2 adet)", calories: 70, protein: 1, carbs: 18, fat: 0 },
    { name: "Üzüm (1 küçük salkım, 100g)", calories: 70, protein: 1, carbs: 18, fat: 0 },
    { name: "Çilek (100g)", calories: 32, protein: 1, carbs: 8, fat: 0 },
    { name: "Karpuz (2 dilim, 200g)", calories: 60, protein: 1, carbs: 15, fat: 0 },
    { name: "Kavun (2 dilim, 200g)", calories: 55, protein: 1, carbs: 13, fat: 0 },
    { name: "Armut (1 adet)", calories: 100, protein: 1, carbs: 27, fat: 0 },
    { name: "Şeftali (1 adet)", calories: 60, protein: 1, carbs: 14, fat: 0 },
    { name: "Kiraz (10 adet)", calories: 50, protein: 1, carbs: 12, fat: 0 },
    { name: "Kivi (1 adet)", calories: 50, protein: 1, carbs: 12, fat: 0 },
    { name: "Ananas (2 dilim)", calories: 80, protein: 1, carbs: 20, fat: 0 },
    { name: "Nar (1 adet)", calories: 130, protein: 2, carbs: 31, fat: 1 },
    { name: "İncir (2 adet)", calories: 80, protein: 1, carbs: 20, fat: 0 },
    { name: "Hurma (3 adet)", calories: 100, protein: 1, carbs: 25, fat: 0 },
  ],
  "🌰 Kuruyemiş & Atıştırmalık": [
    { name: "Badem (10 adet)", calories: 70, protein: 3, carbs: 3, fat: 6 },
    { name: "Ceviz (4 yarım)", calories: 100, protein: 2, carbs: 2, fat: 10 },
    { name: "Fıstık (1 avuç, 30g)", calories: 170, protein: 7, carbs: 6, fat: 14 },
    { name: "Fındık (10 adet)", calories: 90, protein: 2, carbs: 2, fat: 9 },
    { name: "Antep fıstığı (1 avuç)", calories: 160, protein: 6, carbs: 8, fat: 13 },
    { name: "Leblebi (1 avuç, 30g)", calories: 120, protein: 6, carbs: 20, fat: 2 },
    { name: "Kaju (10 adet)", calories: 90, protein: 2, carbs: 5, fat: 7 },
    { name: "Kuru incir (3 adet)", calories: 110, protein: 1, carbs: 28, fat: 0 },
    { name: "Kuru kayısı (5 adet)", calories: 80, protein: 1, carbs: 21, fat: 0 },
    { name: "Kuru üzüm (1 avuç)", calories: 90, protein: 1, carbs: 23, fat: 0 },
    { name: "Bisküvi (petit beurre, 3 adet)", calories: 90, protein: 1, carbs: 15, fat: 3 },
    { name: "Gofret (1 adet)", calories: 130, protein: 2, carbs: 18, fat: 6 },
    { name: "Çikolata (sütlü, 2 kare)", calories: 100, protein: 1, carbs: 11, fat: 6 },
    { name: "Çikolata (bitter, 2 kare)", calories: 90, protein: 1, carbs: 9, fat: 6 },
    { name: "Kraker (5 adet)", calories: 80, protein: 2, carbs: 14, fat: 2 },
    { name: "Mısır cipsi (küçük paket)", calories: 150, protein: 2, carbs: 20, fat: 7 },
    { name: "Granola bar (1 adet)", calories: 200, protein: 4, carbs: 30, fat: 7 },
  ],
  "🥤 İçecek": [
    { name: "Su (1 bardak)", calories: 0, protein: 0, carbs: 0, fat: 0 },
    { name: "Çay (şekersiz)", calories: 2, protein: 0, carbs: 0, fat: 0 },
    { name: "Çay (1 şekerli)", calories: 30, protein: 0, carbs: 8, fat: 0 },
    { name: "Türk kahvesi (sade)", calories: 5, protein: 0, carbs: 0, fat: 0 },
    { name: "Türk kahvesi (orta şekerli)", calories: 30, protein: 0, carbs: 7, fat: 0 },
    { name: "Filtre kahve (sütlü)", calories: 50, protein: 2, carbs: 5, fat: 2 },
    { name: "Latte (orta boy)", calories: 150, protein: 8, carbs: 15, fat: 6 },
    { name: "Taze sıkılmış portakal suyu (1 bardak)", calories: 110, protein: 2, carbs: 26, fat: 0 },
    { name: "Meyve suyu (hazır, 1 kutu)", calories: 130, protein: 0, carbs: 32, fat: 0 },
    { name: "Kola (1 kutu, 330ml)", calories: 140, protein: 0, carbs: 39, fat: 0 },
    { name: "Kola (light, 1 kutu)", calories: 2, protein: 0, carbs: 0, fat: 0 },
    { name: "Limonata (1 bardak)", calories: 100, protein: 0, carbs: 25, fat: 0 },
    { name: "Protein shake (1 porsiyon)", calories: 150, protein: 25, carbs: 8, fat: 3 },
  ],
};

export const ALL_KEY = "⭐ Tümü";
export const CATEGORY_KEYS = Object.keys(quickFoodCategories);
